### ISSUE TITLE
Group all wine apps into single menu folder

### ISSUE THREAD

**Issue by drolyk** [NP-Hardass/wine-overlay#1]
It would be great to have wine menu  folder with grouped apps from wine package - explorer, wine-cfg, winte-tricks
![ubuntu-wine-menu](https://cloud.githubusercontent.com/assets/113742/6019425/602bd664-abb1-11e4-8fd9-a6a242668f21.png)

**Comment by drolyk** [comment]
Now all wine tools go to others folder and installed app to separate menu folder
![6](https://cloud.githubusercontent.com/assets/113742/6019471/dd5062d6-abb1-11e4-943c-bcea7eccd1d2.png)
![7](https://cloud.githubusercontent.com/assets/113742/6019483/0450a3f0-abb2-11e4-9608-d78ccef9dcc5.png)

**Comment by NP-Hardass** [comment]
This is resolved for all but MATE due to an upstream menu issue.  I'll update with a  bug number later.
