### ISSUE TITLE
Update gstreamer pre/post patches

### ISSUE THREAD

**Issue by slackner** [NP-Hardass/wine-overlay#5]
wine-9999 and the next wine release will need an updated version of the gstreamer pre/post patch. There are now several wine-staging patches changing stuff in this area, so it doesn't make sense to revert just a single patchset. The following patch contains only the conflicting areas (from multiple patchsets). I've already tested that it compiles fine.

pre-patch: http://ix.io/gYp
post-patch: http://ix.io/gYq

**Comment by NP-Hardass** [comment]
For reference, conflicting patch is https://github.com/wine-compholio/wine-staging/commit/5fe90fc2e8b11630e9fb6bc832f531f5cc096e5a
